### ISSUE TITLE
Deployment Target < 13

### ISSUE THREAD

**Issue by Jon889** [ethanhuang13/NSAttributedStringBuilder#1]
Is it safe to use this in an app that has a deployment target lower than iOS 13. I know the use of `some Protocol` is not safe to use (which doesn't seem to be used in this library), but unsure about function builders and so on?

**Comment by ethanhuang13** [comment]
Indeed. I used `some` in v0.1 but then removed because it's unnecessary. I'll update the requirement later.

**Comment by Jon889** [comment]
Awesome thanks :)
